type token =
  | PACKAGE | IMPORT | FUNC | FOR | IF | ELSE | RETURN | VAR | RANGE
  | TYPE | STRUCT | CONST | DEFER | GO | SWITCH | CASE | DEFAULT
  | MAP | INTERFACE | CHAN
  | MAKE | NEW | DELETE | REAL | IMAG | COMPLEX | COPY | RECOVER | PANIC | APPEND | CAP | LEN | CLOSE
  | IOTA
  | TRUE | FALSE | NIL
  | IDENT of string
  | STRUCT_ID of string   (* NUEVO: Token para nombres con Mayúscula *)
  | INTLIT of int64
  | FLOATLIT of float
  | STRINGLIT of string
  | ASSIGN
  | DECL_ASSIGN
  | COLON
  | ELLIPSIS
  | PLUS | MINUS | STAR | SLASH | MOD
  | AMP | PIPE | CARET
  | SHL | SHR
  | ARROW
  | EQ_EQ | NOT_EQ | LT | GT | LTE | GTE
  | AND_AND | OR_OR
  | BANG
  | INC | DEC
  | PLUS_ASSIGN | MINUS_ASSIGN | STAR_ASSIGN | SLASH_ASSIGN | MOD_ASSIGN
  | AMP_ASSIGN | PIPE_ASSIGN | CARET_ASSIGN | SHL_ASSIGN | SHR_ASSIGN
  | AND_NOT | AND_NOT_ASSIGN
  | LPAREN | RPAREN
  | LBRACK | RBRACK
  | LBRACE | RBRACE
  | COMMA
  | DOT
  | SEMICOLON
  | EOF
